# Generated by Django 4.1.7 on 2023-09-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField()),
                ('public_part', models.TextField()),
                ('revoked_list', models.TextField(blank=True)),
                ('shortname', models.CharField(max_length=10, unique=True)),
                ('longname', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('personal_signing', models.CharField(choices=[('A', 'Autosign'), ('D', 'Disabled'), ('R', 'Requires approval')], default='D', max_length=1)),
                ('server_signing', models.CharField(choices=[('A', 'Autosign'), ('D', 'Disabled'), ('R', 'Requires approval')], default='D', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Certificate Authorities',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'CSR uploaded'), ('T', 'Ready to sign'), ('S', 'Signed'), ('E', 'Expired'), ('R', 'Revoked')], default='U', max_length=1)),
                ('csr', models.TextField()),
                ('csr_upload_date', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('P', 'Personal'), ('S', 'Server')], default='P', max_length=1)),
                ('cert', models.TextField(blank=True)),
                ('sign_date', models.DateTimeField(null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_certificate_approver', to=settings.AUTH_USER_MODEL)),
                ('ca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.certificateauthority')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_certificate_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
