# Generated by Django 4.1.7 on 2023-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateauthority',
            options={'verbose_name_plural': 'Certificate Authorities'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='sign_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='shortname',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
