# Generated by Django 4.1.7 on 2023-08-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_alter_certificateauthority_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='purpose',
            field=models.CharField(choices=[('P', 'Personal'), ('S', 'Server')], default='P', max_length=1),
        ),
    ]
