# Generated by Django 4.1.7 on 2023-08-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_certificate_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='revoked_list',
            field=models.TextField(blank=True),
        ),
    ]
